version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: '08:00'
      timezone: America/Sao_Paulo
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /dbtests
    schedule:
      interval: weekly
      day: saturday
      time: '08:00'
      timezone: America/Sao_Paulo
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /cmd/testfixtures
    schedule:
      interval: weekly
      day: saturday
      time: '08:00'
      timezone: America/Sao_Paulo
    groups:
      all:
        patterns:
          - "*"
