version: '3'

services:
  testfixtures:
    image: testfixtures
    depends_on:
      - postgresql
      - mariadb
      - sqlserver
      - cockroachdb
      - clickhouse
      - googlesql
    environment:
      PGPASSWORD: postgres
      PG_CONN_STRING: host=postgresql user=postgres dbname=testfixtures_test port=5432 sslmode=disable
      MYSQL_CONN_STRING: root:mariadb@tcp(mariadb)/testfixtures_test?multiStatements=true
      SQLITE_CONN_STRING: testfixtures_test.sqlite3
      SQLSERVER_CONN_STRING: server=sqlserver;database=master;user id=sa;password=SQL@1server;encrypt=disable
      CRDB_CONN_STRING: host=cockroachdb user=root dbname=defaultdb port=26257 sslmode=disable
      CLICKHOUSE_CONN_STRING: clickhouse://clickhouse:clickhouse@clickhouse:9000/testfixtures_test?debug=false
      GOOGLESQL_CONN_STRING: spanner://projects/test-project/instances/test-instance/databases/testdb

  postgresql:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: testfixtures_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mariadb:
    image: mariadb:11.3
    environment:
      MARIADB_DATABASE: testfixtures_test
      MARIADB_ROOT_PASSWORD: mariadb

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: SQL@1server

  cockroachdb:
    image: cockroachdb/cockroach:v20.1.3
    command: start-single-node --store /cockroach-data --insecure --advertise-host cockroachdb

  clickhouse:
    image: yandex/clickhouse-server:22-alpine
    ports:
      - 9010:9000
      - 8133:8123
    environment:
      CLICKHOUSE_DB: testfixtures_test
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse

  googlesql:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - "19010:9010"
      - "19020:9020"
